### ISSUE TITLE
Feature request: Please add PDF/Code links to the text

### ISSUE THREAD

**Issue by grwlf** [ml-feeds/pwc-feeds#1]
Hi, thank you for your work! Could you please add the said links (especially the PDF one) so I could fetch it directly from reader?

**Comment by impredicative** [comment]
Do you mean to append those links to the Description of each entry?

**Comment by grwlf** [comment]
Yes, correct.

**Comment by impredicative** [comment]
The code URL is now appended to the description text, separated by `\n\n`. How your feed reader renders it is up to it. As for the paper URL, I don't see it in the HTML listing.

**Comment by impredicative** [comment]
As a reminder, this extraction is going to be very fragile. Whenever the structure of the HTML changes meaningfully, it'll break.

**Comment by impredicative** [comment]
I now use `CDATA` and `a href` tag to add the code URL to the description. Let's see how this renders.

**Comment by grwlf** [comment]
Thank you! I can see the github link. Unfortunately, Newsboat reader I use doesn't seem to recognize it as url out of the box. I'll try to investigate details soon, one possible reason is that RSS protocol has special fields for links so adding them to plain text is actualy not enough. So it was not that simple after all, sorry for bothering. I think I should test different modes by myself. Is it possible to run pwc-feeds from a home computer?

**Comment by impredicative** [comment]
First give it a day or two to let new entries come in since the CDATA change.

**Comment by impredicative** [comment]
How is it now for the latest entries? It should be clickable.

**Comment by grwlf** [comment]
I confirm that the reader now detects the code link, thanks! What's the
main problem with PDF link?

пн, 15 июл. 2019 г. в 14:23, Ouroboros Chrysopoeia <notifications@github.com

**Comment by impredicative** [comment]
If you go to the page with the list of posts on the PwC website, that page doesn't seem to contain any links to the actual papers. It does however contain links to the actual code, which is how I could extract them easily.

**Comment by grwlf** [comment]
Actually I could see HTML like this one . The PDF link may be non-trivial to find, but I think it is shown as ordinary `<a>` tag
![image](https://user-images.githubusercontent.com/4477729/61237634-8f47b700-a743-11e9-9fbb-472bac5a2e21.png)

Ref https://paperswithcode.com/paper/a-baseline-for-3d-multi-object-tracking

**Comment by impredicative** [comment]
You've linked to a paper's page, not to the listing page. I only scrape the listing page with the list of new entries, e.g. https://paperswithcode.com/latest

For me to also scrape each paper's page would be a significant change that is currently outside the scope of this repo.

**Comment by grwlf** [comment]
Ah, OK, I see now

**Comment by impredicative** [comment]
At most it's just one extra click for you, so it shouldn't be a major issue.
